In [66]:
import json
import glob
import pandas as pd
import os

In [67]:
def flatten_dict(d, prefix='', level=0):
    for i,j in d.items():
        if isinstance(j, dict):
            yield from flatten_dict(j, f'{prefix}{i}_', level+1)
        else:
            yield f'{prefix}{i}', j

def data_reader(filelist):
    for filename in filelist:
        with open(filename) as f:
            yield dict(flatten_dict(json.load(f)))

In [ ]:
mask_no_estimate = 'solutions/without_estimate/*/*.output.json'
mask_with_estimate = 'solutions/with_estimate/*/*.output.json'
mask_inputs = 'with_sol/*/*.json'

In [71]:
df_no_estimate = pd.DataFrame(data_reader(glob.glob(mask_no_estimate)))
df_no_estimate['instance'] = df_no_estimate['meta_data_instance'].apply(lambda x: x.replace('.json', '').split('/')[-1])
df_no_estimate['instance']

0        kcluster40_050_10_3
1        kcluster40_075_10_1
2        kcluster40_025_20_5
3        kcluster40_050_10_4
4        kcluster40_025_30_2
               ...
265    kcluster160_050_120_5
266     kcluster160_050_80_4
267     kcluster160_075_40_4
268    kcluster160_050_120_1
269    kcluster160_050_120_2
Name: instance, Length: 270, dtype: object

In [72]:
df_with_estimate = pd.DataFrame(data_reader(glob.glob(mask_with_estimate)))
df_with_estimate['instance'] = df_with_estimate['meta_data_instance'].apply(lambda x: x.replace('.json', '').split('/')[-1])
df_with_estimate['instance']

0        kcluster40_050_10_3
1        kcluster40_075_10_1
2        kcluster40_025_20_5
3        kcluster40_050_10_4
4        kcluster40_025_30_2
               ...
265    kcluster160_050_120_5
266     kcluster160_050_80_4
267     kcluster160_075_40_4
268    kcluster160_050_120_1
269    kcluster160_050_120_2
Name: instance, Length: 270, dtype: object

In [74]:
df_input_data = pd.DataFrame(data_reader(glob.glob(mask_inputs)))
df_input_data.rename(columns={
    'info_instance': 'instance'
}, inplace=True)
df_input_data

,qubo_shape,qubo_nnz,qubo_row,qubo_col,qubo_data,offset,initial_estimate,instance,info_additional_info_initial_astimate_algo,info_additional_info_time_limit,info_qubo_multiplication_factor
0,"[40, 40]",1600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-3540.0, -3540.0, -3540.0, -3540.0, -3540.0, ...",54000.0,"[1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, ...",kcluster40_075_30_4,mqlib,4,2
1,"[40, 40]",1600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-1560.0, -1560.0, -1560.0, -1560.0, -1560.0, ...",16000.0,"[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, ...",kcluster40_075_20_1,mqlib,4,2
2,"[40, 40]",1600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-3540.0, -3540.0, -3540.0, -3540.0, -3540.0, ...",54000.0,"[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, ...",kcluster40_075_30_5,mqlib,4,2
3,"[40, 40]",1600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-304.0, -304.0, -304.0, -304.0, -304.0, -304....",1600.0,"[1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, ...",kcluster40_050_10_3,mqlib,4,2
4,"[40, 40]",1600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-380.0, -380.0, -380.0, -380.0, -380.0, -380....",2000.0,"[1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",kcluster40_025_10_1,mqlib,4,2
...,...,...,...,...,...,...,...,...,...,...,...
265,"[160, 160]",25600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-25440.0, -25440.0, -25440.0, -25440.0, -2544...",1024000.0,"[1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, ...",kcluster160_025_80_2,mqlib,4,2
266,"[160, 160]",25600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-6320.0, -6320.0, -6320.0, -6320.0, -6320.0, ...",128000.0,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...",kcluster160_025_40_5,mqlib,4,2
267,"[160, 160]",25600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-6320.0, -6320.0, -6320.0, -6320.0, -6320.0, ...",128000.0,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...",kcluster160_050_40_3,mqlib,4,2
268,"[160, 160]",25600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-25440.0, -25440.0, -25440.0, -25440.0, -2544...",1024000.0,"[0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, ...",kcluster160_050_80_1,mqlib,4,2
269,"[160, 160]",25600,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-57360.0, -57360.0, -57360.0, -57360.0, -5736...",3456000.0,"[1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, ...",kcluster160_025_120_3,mqlib,4,2

In [99]:
df_filtered_input_data = df_input_data[['instance', 'offset', 'initial_estimate',
                                        'info_additional_info_initial_astimate_algo', 'info_additional_info_time_limit']].copy()
# df_input_data
df_filtered_input_data['size'] = df_input_data['qubo_shape'].apply(
    lambda x: x[0])
df_filtered_input_data.rename(columns={
    'info_additional_info_initial_astimate_algo': 'initial_estimate_heuristic',
    'info_additional_info_time_limit': 'initial_estimate_time_limit'
}, inplace=True)
df_filtered_input_data.set_index('instance', inplace=True)
df_filtered_input_data

,offset,initial_estimate,initial_estimate_heuristic,initial_estimate_time_limit,size
instance,,,,,
kcluster40_075_30_4,54000.0,"[1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, ...",mqlib,4,40
kcluster40_075_20_1,16000.0,"[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, ...",mqlib,4,40
kcluster40_075_30_5,54000.0,"[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, ...",mqlib,4,40
kcluster40_050_10_3,1600.0,"[1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, ...",mqlib,4,40
kcluster40_025_10_1,2000.0,"[1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",mqlib,4,40
...,...,...,...,...,...
kcluster160_025_80_2,1024000.0,"[1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, ...",mqlib,4,160
kcluster160_025_40_5,128000.0,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...",mqlib,4,160
kcluster160_050_40_3,128000.0,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...",mqlib,4,160
kcluster160_050_80_1,1024000.0,"[0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, ...",mqlib,4,160
kcluster160_025_120_3,3456000.0,"[1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, ...",mqlib,4,160

In [100]:
selected_columns = [
    'instance',
    'qubo_computed_val',
    'meta_data_time',
    'meta_data_root_node_time',
    'meta_data_root_node_heuristic_run_count',
    'meta_data_root_node_sdp_value',
    'meta_data_root_node_heuristic_value',
    'meta_data_root_node_total_heur_time',
    'meta_data_root_node_root_solution'
]

In [101]:
df_filtered_with_estimate = df_with_estimate[selected_columns].copy()

df_filtered_with_estimate.rename(columns={
    'qubo_computed_val': 'final_qubo_value_w',
    'meta_data_time': 'total_time_w',
    'meta_data_root_node_time': 'root_eval_time_w',
    'meta_data_root_node_heuristic_run_count': 'heur_run_count_w',
    'meta_data_root_node_sdp_value': 'sdp_value_w',
    'meta_data_root_node_heuristic_value': 'heur_value_w',
    'meta_data_root_node_total_heur_time': 'heur_total_time_w',
    'meta_data_root_node_root_solution': 'root_solution_w'
}, inplace=True)

df_filtered_with_estimate.set_index('instance', inplace=True)

df_filtered_no_estimate = df_no_estimate[selected_columns].copy()

df_filtered_no_estimate.rename(columns={
    'qubo_computed_val': 'final_qubo_value',
    'meta_data_time': 'total_time',
    'meta_data_root_node_time': 'root_eval_time',
    'meta_data_root_node_heuristic_run_count': 'heur_run_count',
    'meta_data_root_node_sdp_value': 'sdp_value',
    'meta_data_root_node_heuristic_value': 'heur_value',
    'meta_data_root_node_total_heur_time': 'heur_total_time',
    'meta_data_root_node_root_solution': 'root_solution'
}, inplace=True)
df_filtered_no_estimate.set_index('instance', inplace=True)

In [104]:
df_merged = pd.concat([df_filtered_input_data, df_filtered_with_estimate, df_filtered_no_estimate], axis=1)
df_merged['heur_value_with-no'] = df_merged['heur_value_w'] - df_merged['heur_value']
df_merged['sdp_value_with-no'] = df_merged['sdp_value_w'] - df_merged['sdp_value']
df_merged['gap'] = df_merged['sdp_value'] - df_merged['heur_value']
df_merged['gap_w'] = df_merged['sdp_value_w'] - df_merged['heur_value_w']
df_merged['gap_w-no'] = df_merged['gap_w'] - df_merged['gap']

In [105]:
df_merged

,offset,initial_estimate,initial_estimate_heuristic,initial_estimate_time_limit,size,final_qubo_value_w,total_time_w,root_eval_time_w,heur_run_count_w,sdp_value_w,...,heur_run_count,sdp_value,heur_value,heur_total_time,root_solution,heur_value_with-no,sdp_value_with-no,gap,gap_w,gap_w-no
instance,,,,,,,,,,,,,,,,,,,,,
kcluster40_075_30_4,54000.0,"[1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, ...",mqlib,4,40,162.0,0.495430,0.494981,16,5.383907e+04,...,16,5.383907e+04,53838.0,0.003758,"[1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, ...",0.0,-0.001303,1.074545,1.073242,-0.001303
kcluster40_075_20_1,16000.0,"[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, ...",mqlib,4,40,44.0,0.028844,0.028431,4,1.595679e+04,...,4,1.595679e+04,15956.0,0.000774,"[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, ...",0.0,0.000000,0.789644,0.789644,0.000000
kcluster40_075_30_5,54000.0,"[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, ...",mqlib,4,40,160.0,0.367582,0.367198,16,5.384139e+04,...,16,5.384138e+04,53840.0,0.003336,"[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, ...",0.0,0.007735,1.382317,1.390052,0.007735
kcluster40_050_10_3,1600.0,"[1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, ...",mqlib,4,40,12.0,0.269461,0.268995,16,1.589440e+03,...,16,1.589476e+03,1588.0,0.003755,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0.0,-0.036337,1.476259,1.439922,-0.036337
kcluster40_025_10_1,2000.0,"[1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",mqlib,4,40,32.0,0.541867,0.541420,17,1.968992e+03,...,17,1.968997e+03,1968.0,0.003510,"[1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",0.0,-0.005102,0.996761,0.991660,-0.005102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
kcluster160_025_80_2,1024000.0,"[1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, ...",mqlib,4,160,4236.0,3.141146,3.140626,16,1.019796e+06,...,16,1.019796e+06,1019764.0,0.223714,"[1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, ...",0.0,-0.165382,31.857588,31.692206,-0.165382
kcluster160_025_40_5,128000.0,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...",mqlib,4,160,904.0,3.323332,3.322829,16,1.271225e+05,...,16,1.271226e+05,127094.0,0.262921,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...",2.0,-0.184558,28.641863,26.457305,-2.184558
kcluster160_050_40_3,128000.0,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...",mqlib,4,160,466.0,3.373993,3.373405,16,1.275540e+05,...,16,1.275539e+05,127532.0,0.260614,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, ...",2.0,0.107627,21.927809,20.035437,-1.892373
kcluster160_050_80_1,1024000.0,"[0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, ...",mqlib,4,160,2562.0,3.136832,3.136275,16,1.021454e+06,...,16,1.021454e+06,1021438.0,0.200237,"[0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, ...",0.0,-0.194711,16.440166,16.245455,-0.194711
kcluster160_025_120_3,3456000.0,"[1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, ...",mqlib,4,160,10294.0,3.827923,3.827379,16,3.445746e+06,...,16,3.445746e+06,3445706.0,0.193288,"[1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, ...",0.0,0.005990,40.199397,40.205387,0.005990

In [106]:
df_merged[['heur_value_with-no', 'sdp_value_with-no', 'gap_w-no']].sort_values('heur_value_with-no')

                      heur_value_with-no  sdp_value_with-no  gap_w-no
instance
kcluster140_075_35_2                -8.0           0.078786  8.078786
kcluster160_075_40_3                -4.0           0.162280  4.162280
kcluster160_050_40_4                -4.0           0.080136  4.080136
kcluster140_075_35_1                -2.0          -0.006591  1.993409
kcluster160_075_40_1                -2.0          -0.035882  1.964118
...                                  ...                ...       ...
kcluster160_025_80_4                 2.0           0.137902 -1.862098
kcluster160_025_40_5                 2.0          -0.184558 -2.184558
kcluster160_050_40_3                 2.0           0.107627 -1.892373
kcluster100_025_25_2                 2.0           0.024082 -1.975918
kcluster160_050_40_5                 2.0           0.101591 -1.898409

[270 rows x 3 columns]